# Generated by Django 2.0 on 2018-03-29 02:44

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('ut', models.ForeignKey(on_delete=builtins.callable, to='app01.UserType')),
            ],
        ),
    ]
