# Generated by Django 2.0 on 2018-03-29 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserType'),
        ),
    ]
