# Generated by Django 2.0 on 2018-01-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zabbix_moniter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ip', models.CharField(max_length=20)),
                ('ping', models.IntegerField(null=True)),
                ('disk', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
