# Generated by Django 2.0 on 2018-02-24 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book2Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Author')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book2author',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Book'),
        ),
        migrations.AlterUniqueTogether(
            name='book2author',
            unique_together={('author', 'book')},
        ),
    ]
